<?php

/**
 * @file
 * Contains datatables.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datatables_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the datatables module.
    case 'help.page.datatables':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('loading Datatables Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function datatables_theme() {
  return [
    'datatables' => [
      'render element' => 'children',
    ],
  ];
}
