<?php

/**
 * @file
 * Contains chubb_life.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chubb_life_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chubb_life module.
    case 'help.page.chubb_life':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chubb Life Insurance Company') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chubb_life_theme() {
  return [
    'chubb_life' => [
      'render element' => 'children',
    ],
  ];
}

function chubb_life_cron(){
  \Drupal::logger('chubb_life')->notice('Cron ran');
  $config = \Drupal::service('config.factory')->getEditable('chubb_life.settings');
  $file = "https://stagmtrc.sigmaxu.com/maintenance.txt";
  $data_json = file_get_contents($file);
  $flag = json_decode($data_json);
  \Drupal::logger('chubb_life')->notice('get json: '.$data_json);
  if($flag->payment_fail){
    $config->set('reject_payment', true)->save();
  }else{
    $config->set('reject_payment', false)->save();
  }
  \Drupal::logger('chubb_life')->notice('reject_payment: '.$config->get('reject_payment'));
}