<?php

/**
 * @file
 * Contains chubb_life.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chubb_life_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chubb_life module.
    case 'help.page.chubb_life':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chubb Life Insurance Company') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chubb_life_theme() {
  return [
    'chubb_life' => [
      'render element' => 'children',
    ],
  ];
}
