CREATE TABLE `mtrc`.`mtrc_customer_import` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cust_ref` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `tel_mbl` VARCHAR(45) NULL,
  `tel_hom` VARCHAR(45) NULL,
  `hkid` VARCHAR(45) NULL,
  `acc_no` VARCHAR(45) NULL,
  `card_brand` VARCHAR(45) NULL,
  `card_type` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  `married_status` VARCHAR(45) NULL,
  `address` MEDIUMTEXT NULL,
  `living_person` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `member_since` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));
