version: "3.9"
services:
  webserver:
    build: ./docker/php/
    container_name: php81-apache
    ports:
      - "8081:80"
      # - "443:443"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0
    container_name: mysql-80
    volumes:
      - ./docker/mysql/mtrc.sql:/docker-entrypoint-initdb.d/mtrc.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mtrc
    ports:
      - "33061:3306"