<?php

/**
 * @file
 * Contains development.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function development_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the development module.
    case 'help.page.development':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Make The Right Call Development') . '</p>';
      return $output;

    default:
  }
}
function development_cron(){
  $slogan = \Drupal::service('config.factory')->getEditable('system.site')->get('slogan');
  if(is_numeric($slogan)){
    \Drupal::service('config.factory')->getEditable('system.site')->set('slogan',$slogan)->save();
  }else{
    \Drupal::service('config.factory')->getEditable('system.site')->set('slogan',0)->save();
  }
}
/**
 * Implements hook_theme().
 */
function development_theme() {
  return [
    'development' => [
      'render element' => 'children',
    ],
  ];
}
