DROP TABLE IF EXISTS `mtrc_order`;
CREATE TABLE `mtrc_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `referenceNumber` varchar(45) DEFAULT NULL,
  `aeonRefNumber` varchar(45) DEFAULT NULL,
  `same_as_owner` varchar(45) DEFAULT NULL,
  `beneficiary_relationship` varchar(45) DEFAULT NULL,
  `currency` varchar(45) DEFAULT NULL,
  `paymentMode` varchar(45) DEFAULT NULL,
  `pep` varchar(45) DEFAULT NULL,
  `another_person` varchar(45) DEFAULT NULL,
  `ecopy` varchar(45) DEFAULT NULL,
  `plan_code` varchar(45) DEFAULT NULL,
  `face_amount` varchar(45) DEFAULT NULL,
  `plan_level` varchar(45) DEFAULT NULL,
  `family_package` varchar(45) DEFAULT NULL,
  `replacement_declaration` varchar(45) DEFAULT NULL,
  `fna` varchar(45) DEFAULT NULL,
  `health_details_q_1` varchar(45) DEFAULT NULL,
  `health_details_q_2` varchar(45) DEFAULT NULL,
  `health_details_q_3` varchar(45) DEFAULT NULL,
  `health_details_q_4` varchar(45) DEFAULT NULL,
  `health_details_q_5` varchar(45) DEFAULT NULL,
  `agentCode` varchar(45) DEFAULT NULL,
  `billingType` varchar(45) DEFAULT NULL,
  `authorizationCode` varchar(45) DEFAULT NULL,
  `cardHolderName` varchar(45) DEFAULT NULL,
  `cardholder_id_number` varchar(45) DEFAULT NULL,
  `card_expiry_date` varchar(45) DEFAULT NULL,
  `initial_premium` varchar(45) DEFAULT NULL,
  `modal_premium_payment` varchar(45) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `created_at` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `mtrc_order_client`;
CREATE TABLE `mtrc_order_client` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) DEFAULT NULL,
  `client_type` int(11) DEFAULT NULL,
  `surname` varchar(45) DEFAULT NULL,
  `givenName` varchar(45) DEFAULT NULL,
  `chineseName` varchar(45) DEFAULT NULL,
  `relationship` varchar(45) DEFAULT NULL,
  `identityType` varchar(45) DEFAULT NULL,
  `identityNumber` varchar(45) DEFAULT NULL,
  `issueCountry` varchar(45) DEFAULT NULL,
  `gender` varchar(45) DEFAULT NULL,
  `isPermanentHkid` varchar(45) DEFAULT NULL,
  `birthDate` varchar(45) DEFAULT NULL,
  `marital` varchar(45) DEFAULT NULL,
  `nationality` varchar(45) DEFAULT NULL,
  `taxResidency1` varchar(45) DEFAULT NULL,
  `taxResidencyTin1` varchar(45) DEFAULT NULL,
  `taxResidency2` varchar(45) DEFAULT NULL,
  `taxResidencyTin2` varchar(45) DEFAULT NULL,
  `taxResidency3` varchar(45) DEFAULT NULL,
  `taxResidencyTin3` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `residence_address1` varchar(45) DEFAULT NULL,
  `residence_address2` varchar(45) DEFAULT NULL,
  `residence_address3` varchar(45) DEFAULT NULL,
  `residence_city` varchar(45) DEFAULT NULL,
  `residence_country` varchar(45) DEFAULT NULL,
  `mailing_address1` varchar(45) DEFAULT NULL,
  `mailing_address2` varchar(45) DEFAULT NULL,
  `mailing_address3` varchar(45) DEFAULT NULL,
  `mailing_city` varchar(45) DEFAULT NULL,
  `mailing_country` varchar(45) DEFAULT NULL,
  `occupationCode` varchar(45) DEFAULT NULL,
  `mobile` varchar(45) DEFAULT NULL,
  `smoker` varchar(45) DEFAULT NULL,
  `monthly_income` varchar(45) DEFAULT NULL,
  `solicitation` varchar(45) DEFAULT NULL,
  `opt_out_reason` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
