name: Deploy Workflow
on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:
jobs:
  deploy_staging:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: STAG
    steps:
      - uses: actions/checkout@v3
      - name: rsync file to folder
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ALI_STAGE_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SSH_ALI_STAGE_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/mtrc
          # EXCLUDE: "/src/"
      # - name: drupalconsole update cr
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_STAGE_HOST }}
      #     username: root
      #     key: ${{ secrets.SSH_STAGE_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       whoami
      #       cat << EOF >> /var/www/mtrc/sites/stag/settings.php
      #       ${{ secrets.STAG_MTRC_SETTINGS }}
      #       EOF
      #       cd /var/www/mtrc
      #       chmod -R 777 sites/stag/files/
      #       vendor/bin/drupal --uri=stagmtrc.sigmaxu.com update:execute system
      #       vendor/bin/drupal --uri=stagmtrc.sigmaxu.com cr all
  # deploy_production:
  #   runs-on: ubuntu-latest
  #   environment: PRODUCTION
  #   needs: deploy_staging
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: rsync file to folder
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         ARGS: "-avzr --delete"
  #         SOURCE: ""
  #         REMOTE_HOST: ${{ secrets.SSH_HOST }}
  #         REMOTE_USER: root
  #         TARGET: /var/www/f4f_erp
  #         # EXCLUDE: "/dist/, /node_modules/"
  #     - name: drupalconsole update cr
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: root
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: 22
  #         script: |
  #           whoami
  #           cat << EOF >> /var/www/f4f_erp/sites/prod/settings.php
  #           ${{ secrets.PRODUCTION_SETTINGS }}
  #           EOF
  #           cd /var/www/f4f_erp
  #           chmod -R 777 sites/prod/files/
  #           chmod -R 777 sites/prod/files/f4f/
  #           vendor/bin/drupal --uri=erp.first4figures.com update:execute system
  #           vendor/bin/drupal --uri=erp.first4figures.com cr all
